### ISSUE TITLE
QA問答送出按鈕增加防呆

### ISSUE THREAD

**Issue by Jackson45252** [MOPCON/App-Android#138]
雖然沒有選擇答案，但仍然能送出，麻煩加上防呆以免使用者誤觸
![screenshot_20181021-202624](https://user-images.githubusercontent.com/9023148/47267127-f9934880-d571-11e8-96f9-b4a8434cbdcd.png)

**Comment by chnbohwr** [comment]
可以再提供詳細一點的操作步驟嘛

**Comment by Jackson45252** [comment]
點進去任務畫面>按下送出按鈕>出現[跳戰失敗，下回再加油！]

希望能增加沒有選擇答題選項的話，送出按鈕要能 disabled

**Comment by chnbohwr** [comment]
#142 fixed.
