### ISSUE TITLE
QA 文字顯示跑版&不完全

### ISSUE THREAD

**Issue by Jackson45252** [MOPCON/App-Android#145]
![oepcs50](https://user-images.githubusercontent.com/9023148/47283718-074ed980-d617-11e8-8560-d1ab98511573.png)

> 文字太長會被截掉

![viz51oz](https://user-images.githubusercontent.com/9023148/47283716-04ec7f80-d617-11e8-813e-44b6b303bab6.png)

> 顯示得1，錢包有正確+10

測試手機版本 Android 6.0.0

**Comment by chnbohwr** [comment]
請問一下手機的解析度

**Comment by chnbohwr** [comment]
#146  fixed
