### ISSUE TITLE
將2018 MOPCON專案build起來

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#161]
- 確認功能正常，並且無破版
- [x] Android 模擬器
- [ ] Android 實機

**Comment by chnbohwr** [comment]
沒有實機，到時候再借一支，模擬器已經跑過沒問題
![image](https://user-images.githubusercontent.com/6761222/57231174-9ae47680-704c-11e9-86bd-eb5b26cf38e6.png)
