### ISSUE TITLE
熟悉專案架構並提出可改善部分

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#162]
可改善部分請列在下方comment

**Comment by chnbohwr** [comment]
1. 今年若有小遊戲，需改由 API 後端計算分數
2. QR Code 的套件不太穩定，建議今年別玩  QR Code

**Comment by TKDchampion** [comment]
1. 啟動顯示畫面( SplashScreen)，過久看是否能優化，建議加上進度條
2. 看套件是否有要跟著升級成最新版本

**Comment by bbandydd** [comment]
@chnbohwr 
1 跟 2 要等組長確認今年大地遊戲內容才知道怎麼做，你的意見會跟組長提醒

@TKDchampion 
1. 這個意見很好，可以減少使用者不耐煩的心態，那下個Sprint就開Issue來做
2. 可以列出哪些套件要升級，升級後有什麼優點或影響嗎？
