### ISSUE TITLE
Study CI/CD作法，使用AppCenter

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#163]
- [App Center](https://appcenter.ms/)
- 包含打包至上架到google play

**Comment by chnbohwr** [comment]
目前會先把 travis 修理好 master 回復到乾淨的 v2.0.6版本，請幫我把阿淵邀請進來專案開發者內

**Comment by bbandydd** [comment]
已加入阿淵

**Comment by chnbohwr** [comment]
#165 已經把 App Center 完成
