### ISSUE TITLE
改善mopcon app發想

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#178]
來發想一下吧
之前做的改善是針對Coding Style及架構設計

那我們來發想一下有沒有做法可以優化app 畫面維護
根據目前mopon app的定位
除了大地遊戲之外的功能及畫面都固定了
之後就根據美術組的要求換圖換色系換字

以這為前提大家來提一下想法

**Comment by chnbohwr** [comment]
1. 提議未來 ios web push notification 開放以後，我們可以用 PWA 技術來做 APP ，不用透過 store 安裝了，省3600，網站寫好以後 ios / android 都做好了
 
2. kktix oatuh 整合，我們每次小遊戲都在想說使用者重新安裝怎麼辦，若是 kktix 有 oauth 可以用就不用煩惱了，還可以依據使用者購票種類顯示不同的 App 底色，或是開通不同的 App 功能，不過我目前查好像 kktix 沒有提供這麼詳細的 api
