### ISSUE TITLE
首頁樣式調整 

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#203]
- [ ] 上方多了一個圖片輪播功能，先把畫面做上去，API到時候再討論

![螢幕快照 2019-07-28 下午11 48 19](https://user-images.githubusercontent.com/11688424/62009470-3ab82900-b192-11e9-9605-3d6ad7fe614b.png)

**Comment by chnbohwr** [comment]
added carousel image demo

#208
