### ISSUE TITLE
議程樣式調整

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#204]
- [x] 新增交流場次頁籤
- [x] 廳別顯示移除顏色標示、使用與去年相同的顯示廳別方式，R1: 一廳

![螢幕快照 2019-07-28 下午11 52 23](https://user-images.githubusercontent.com/11688424/62009531-e2355b80-b192-11e9-83a3-eed81de8a4f5.png)

- [ ] 演講資訊樣式調整

![螢幕快照 2019-07-28 下午11 52 45](https://user-images.githubusercontent.com/11688424/62009549-1d378f00-b193-11e9-8976-aa91d30f5879.png)

**Comment by chnbohwr** [comment]
下方贊助商的顯示等 API 有做了再補上
