### ISSUE TITLE
initial api、主辦社群、贊助商、志工 API

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#215]
畫面已經調整為2019樣式了，接下來就把API接上吧
API相關資訊如下方連結

initial api 推上去了
- https://mopcon.org/api/2019/initial
- https://github.com/MOPCON/MOPCON/blob/develop/api/docs/initial.md
主辦社群
- https://mopcon.org/api/2019/community
- https://github.com/MOPCON/MOPCON/blob/develop/api/docs/community.md
贊助商
- https://github.com/MOPCON/MOPCON/blob/develop/api/docs/sponsor.md
- https://mopcon.org/api/2019/sponsor
志工
- https://github.com/MOPCON/MOPCON/blob/develop/api/docs/volunteer.md
- https://mopcon.org/api/2019/volunteer

**Comment by chnbohwr** [comment]
@bbandydd @hashman 
這個 issue 已經完成 在 feature/api_2019 分支
我目前先不合併，等到所有 api 串完我再一併合

尚有疑慮的部份：
1. 贊助商Detail 頁面，裡面要有演講資訊，但是 API 目前只有給贊助商講者，這個等到後端修正，下個 sprint 我再做
2. 主辦社群，協辦社群部份我等 UI 好了我再做
