### ISSUE TITLE
社群頁面調整

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#221]
05.4 - 社群  ==> 分出主辦社群、參與社群
05.4.1 - 社群資訊 ==> 增加社群連結icon

**Comment by chnbohwr** [comment]
add comminity detail icon 
https://github.com/MOPCON/App-Android/commit/d2c609c745c224978a050e0b09cd2d098d0468f1

participant 
https://github.com/MOPCON/App-Android/commit/cecafa72854566f790dd665f753291a478368049
