### ISSUE TITLE
串接議程API

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#224]
https://github.com/MOPCON/MOPCON/blob/develop/api/docs/session.md

- [Tag對照](https://hackmd.io/Uf3vjIlASoqxqS6sXaMMMw)
  - tech (藍)
  - design (綠)
  - other (紅)

**Comment by chnbohwr** [comment]
done

https://github.com/MOPCON/App-Android/commit/3f9048156c4bc14fdda73d0fcafbb3b8b287480f
