### ISSUE TITLE
Develop branch issues

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#237]
下面這些問題都是在develop分支build到實機上測試出來的

## 首頁

-  上方跑馬燈圖片沒出現

![11227](https://user-images.githubusercontent.com/11688424/65381179-a1833a00-dd1e-11e9-90d2-15d002d50046.jpg)

## 大地遊戲

- 掃描QRCode完成後，遺漏這個Modal顯示任務完成
![1569116099732](https://user-images.githubusercontent.com/11688424/65381119-dee6c800-dd1c-11e9-90a1-4251af5322dc.jpg)

- 關卡未全部完成時，領取獎勵那格背景色就已經是完成的樣子，因為沒截到圖我用改圖的方式顯示
![螢幕快照 2019-09-22 上午9 47 29](https://user-images.githubusercontent.com/11688424/65381154-038f6f80-dd1e-11e9-8ef4-a17f4589c35f.png)

- 關卡全部完成時，領取獎勵無法點擊
![11226](https://user-images.githubusercontent.com/11688424/65381168-5bc67180-dd1e-11e9-9c57-2918e109b3b5.jpg)

**Comment by chnbohwr** [comment]
跑馬燈沒有出現，是因為 api 給的 圖片連結有問題

**Comment by chnbohwr** [comment]
fixed. #242
