### ISSUE TITLE
text break when locale is Eng

### ISSUE THREAD

**Issue by chnbohwr** [MOPCON/App-Android#26]
![image](https://user-images.githubusercontent.com/6761222/41601234-7a0dbfaa-740a-11e8-9778-aee430e21bab.png)

**Comment by bbandydd** [comment]
我是想說等英文語系翻譯確認後再調，怕現在調完之後又要調

**Comment by chnbohwr** [comment]
左右 padding 40px 太大，文字可以輸入的數量變成很少，先做了簡單的處理讓可以塞的文字變多，待之後塞不下再與設計師討論。
