### ISSUE TITLE
大地遊戲 UI

### ISSUE THREAD

**Issue by Hinrick** [MOPCON/App-Android#274]
完成大地遊戲新版 UI

## Flow - 闖關
- [x] 歡迎訊息
- [x] 破關進度條: 一/二階段
- [x] 任務關卡說明
- [x] 掃描 QR Code
- [x] Puzzle
- [x] 任務完成訊息
- [x] 獲得獎勵訊息
- [x] 全通關訊息

## Flow - 獎勵兌換
- [x] 我的獎勵一覽
- [x] 獎勵兌換

**Comment by RaphaHsu** [comment]
solved all tasks, close
