### ISSUE TITLE
add scan QR code package

### ISSUE THREAD

**Issue by chnbohwr** [MOPCON/App-Android#63]

**Comment by chnbohwr** [comment]
方案 1 ac-qrcode
https://github.com/MarnoDev/AC-QRCode-RN

方案 2 react-native-qrcode-scanner
https://github.com/moaazsidat/react-native-qrcode-scanner

方案3 react-native-camera
https://github.com/react-native-community/react-native-camera

**Comment by bbandydd** [comment]
using  react-native-qrcode-scanner

https://github.com/MOPCON/App-Android/pull/69
