### ISSUE TITLE
community  connect api data

### ISSUE THREAD

**Issue by chnbohwr** [MOPCON/App-Android#75]

**Comment by bbandydd** [comment]
@Jackson45252 
3. 我覺得都可以，主要是拿來判斷選擇到哪一筆
6. 那如果有其他連結的話，參數應該是什麼呢

**Comment by Jackson45252** [comment]
@bbandydd 第6. 之後會改成[這個格式 ](https://github.com/MOPCON/MOPCON/issues/109)

**Comment by bbandydd** [comment]
缺少logo
