### ISSUE TITLE
speaker connect api data

### ISSUE THREAD

**Issue by bbandydd** [MOPCON/App-Android#80]

**Comment by bbandydd** [comment]
<img width="245" alt="2018-08-22 12 46 46" src="https://user-images.githubusercontent.com/11688424/44416199-dd405300-a5a4-11e8-9da3-1f51f7f084b4.png">
1. UI出的圖有講者的公司或單位，api沒看到
2. job只有中文，會有英文嗎？

**Comment by chnbohwr** [comment]
我有動到 speaker item ， 再請 andy 留意一下。

https://github.com/MOPCON/App-Android/compare/feature/speach_detail_api?expand=1#diff-9ddca3548746013b565981921a4c9fce

**Comment by bbandydd** [comment]
@chnbohwr 有修正了，不過名字下方的公司或單位不是放info，等後端資料出來再一併修正

**Comment by chnbohwr** [comment]
got it 
到時你改完 speakeritem 以後我再修正

**Comment by Jackson45252** [comment]
@bbandydd 
1.公司或單位 其實就包含在 job 裡了，所以欄位不用重複
2.議程組回覆說不用做雙語

**Comment by chnbohwr** [comment]
這樣需要上 slack 請 ui ux 來變更設計嘛？ @Jackson45252

**Comment by Jackson45252** [comment]
@chnbohwr  我剛看了一下設計稿，好像是為了分成兩行顯示，我再請後端多開一個 company 好了
